### PR TITLE
Expose async-function argument type

### PR DESCRIPTION
**Pull request by viktorlott**
We are exposing the async-function argument type for jsDoc
type declaration support. This means that we now could do:
`npm i -D @types/github-script@github:actions/github-script`
and the add:
`@param {import('@types/github-script').AsyncFunctionArguments} AsyncFunctionArguments`.

This could obviously be done in other ways too, like using
`@typed-actions/github-script` instead. But it seems better
to use the actual source repository instead of a third-party
library to import the type declaration.

### CODE REVIEW

**Comment by joshmgross** [comment]
👋 Hey @viktorlott,

This is definitely an interesting idea, but I'm concerned this would push users in the wrong direction. If you're writing fully typed scripts and creating composite actions, you're probably better off just writing your own action - https://github.com/actions/typescript-action

Could you share a bit more about your use case?

**Comment by homura** [comment]
`actions/typescript-action` is too heavy for someone just wants to create a non-generic workflow. 

> Could you share a bit more about your use case?

For me, what I want is for the editor to be able to intelligently suggest when writing a workflow, because `github`, `context` and so on have too many APIs, and being able to suggest intelligently would help to avoid switching back and forth between the document and the code

Additionally, the exported types maybe an alternative to issue https://github.com/actions/github-script/issues/294

**Review by joshmgross — COMMENTED** [review]
@viktorlott I'm okay with adding these types, but I'd like to think a bit more about how extensively we document alternative setups. I still think it pushes users in the wrong direction about how to use this action, so I'm reluctant to document it as something we fully support and encourage.

Would you be willing to remove the documentation in `docs/alternative-setup.md`?
We could put it in an discussion for now for users adopting more advanced scenarios.

**Comment by viktorlott** [comment]
@joshmgross Oh hey, I totally forgot about this PR.

> Would you be willing to remove the documentation in docs/alternative-setup.md?
> We could put it in a discussion for now for users adopting more advanced scenarios.

I understand what you mean, and I'm totally fine with that; so I'll push a revision of this when I get home from work. Cheers!

**Review by joshmgross — APPROVED** [review]

**Comment by yusoh** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
</head>
<body>
    <h1>Hello World!</h1>
    <p>
        We are using Node.js <span id="node-version"></span>,
        Chromium <span id="chrome-version"></span>,
        and Electron <span id="electron-version"></span>.
    </p>
</body>
</html>

**Pull request merged**
