### PR TITLE
Update dependencies 2021-06-26

### LINKED ISSUE #133: TypeError: github.repos.createOrUpdateEnvironment is not a function - Octokit.js Support up-to-date?
**Is your feature request related to a problem? Please describe.**
Trying to use github-script for environments but getting this error message:
`TypeError: github.repos.createOrUpdateEnvironment is not a function`

**Describe the solution you'd like**
Would you all be able to update the version of Octokit.js that supports [Repo Environments](https://octokit.github.io/rest.js/v18#repos-create-or-update-environment)

**Describe alternatives you've considered**
Using actions to post the HTTP response for environment creation

**Additional context**
image

### PR DESCRIPTION
**Pull request by Simran-B**
Update dependencies to latest except husky (v5 moves to a somewhat messy file-based approach, but let me know if you want to upgrade anyway).

Fixes #133 and #155.

**Breaking changes:**

REST endpoint methods are now exposed under a nested object `rest` by Octokit. For `github-script`, this means that endpoints are now accessed via `github.rest.{endpoint}` rather than `github.{endpoint}`. Also see:
- https://github.com/actions/toolkit/pull/783
- https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.0.0

jest 27 removes support for Node.js 11 and 13 (now only supporting LTS versions and Node.js 15). You may want to up the Node.js version in this workflow: https://github.com/actions/github-script/blob/672319273b99e5d021fb4bec8aeb79ec84c6d772/.github/workflows/ci.yml#L13

### CODE REVIEW

**Comment by joshmgross** [comment]
>jest 27 removes support for Node.js 11 and 13 (now only supporting LTS versions and Node.js 15). You may want to up the Node.js version in this workflow

Thanks! Since javascript actions are run on Node 12 LTS, we should be using that in the workflow rather than 13.

**Comment by joshmgross** [comment]
I updated the workflows in https://github.com/actions/github-script/pull/159 to resolve that issue with Jest.


It looks like the Licensed check is failing, let me know if you need help updating that. https://github.com/actions/github-script/pull/156/checks?check_run_id=2935017298

**Comment by Simran-B** [comment]
@joshmgross The licenses should be sorted out.

I noticed that the pre-commit hook runs under Linux, but I believe it didn't under Windows. Maybe a reason to upgrade husky after all, but that can be a separate PR and I also need to test this again in a clean Windows environment.

**Review by duongxuantuan154 — APPROVED** [review]
- [ ]

**Comment by Timmmy-nlb** [comment]
Sorry, but is there something I can do to help on this PR to solve issue #155?

**Comment by Simran-B** [comment]
The maintainers would only need to merge the PR, then tag and release the changes as v5 (semver-major as it contains breaking changes).

**Pull request closed without merging**
