### PR TITLE
Update `@octokit/plugin-rest-endpoint-methods` to version 6.x

### PR DESCRIPTION
**Pull request by desrosj**
This updates the dependency to the latest version within current SemVer constraints.

[v5.14.0](https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.14.0) specifically includes a number of new endpoints, including `.rest.actions.reRunWorkflowFailedJobs()`, which is the one I am trying to use when discovering this issue. Currently the following error is given:

`Error: Unhandled error: TypeError: github.rest.actions.reRunWorkflowFailedJobs is not a function`

### CODE REVIEW

**Comment by desrosj** [comment]
There is a [v16.0.0](https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v6.0.0), however this version drops support for NodeJS v10 & v12. Happy to update this PR if these versions are no longer supported.

**Comment by joshmgross** [comment]
> Happy to update this PR if these versions are no longer supported.

The latest version of this action is using Node 16, so I'm good with updating to the latest version

https://github.com/actions/github-script/blob/main/action.yml#L29-L30

**Comment by desrosj** [comment]
I've updated the version to the latest ([v6.3.0](https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v6.3.0)).

I also noticed that the version numbers in the `package.json` and `package-lock.json` files were not updated for versions 6.1 and 6.1.1. I bumped these to values to 6.2.0 to make it easier to tag the next release after this PR is merged.

**Review by joshmgross — APPROVED** [review]
Thanks for this!

I can push changes to update the licenses.

Since the only breaking changes are dropping support for Node 10 and 12 which won't affect this action, I don't think we need a major version bump to v7 for `actions/github-script`

**Comment by joshmgross** [comment]
Available in https://github.com/actions/github-script/releases/tag/v6.2.0

**Pull request merged**
