### PR TITLE
update plugin dependencies

### PR DESCRIPTION
**Pull request by PeterNitscheMI**
Some REST API functions are missing which are described in the octakit documentation (https://octokit.github.io/rest.js/v18/). I need the github.rest.check.rerequestRun in my workflow.

Thus, I have updated the plugin dependencies to the latest version.

### CODE REVIEW

**Comment by PeterNitscheMI** [comment]
Hey @joshmgross :-) Can you help me to bring this change on the road? We are currently blocked by the missing API. Thanks :-)

**Comment by antdking** [comment]
> Hey @joshmgross :-) Can you help me to bring this change on the road? We are currently blocked by the missing API. Thanks :-)

A temporary workaround you can do is to use the `.request` method.

[Example Usage](https://github.com/FundingOptions/actions/blob/5e0523f26524b047d24d2792eb1811a4ccfb3670/release/upsert-release.js#L43)

Reference for how to use:
https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/dfc6f585ded8ca5a7bf747bf03a6b62edec40559/src/generated/endpoints.ts#L335

**Comment by joshmgross** [comment]
👋 Hey @PeterNitscheMI,

It looks like some licenses are out of date after this change https://github.com/actions/github-script/runs/4385889733?check_suite_focus=true


These are managed via the licensed tool - https://github.com/github/licensed

Let me know if you need help getting those updated.

**Comment by PeterNitscheMI** [comment]
Hey @joshmgross ,

sorry for letting you wait so long. 
I have updated the license cache using the `licensed cache` command of licensed version 2.12.2. 
A lot of licenses have been removed and I'm not sure if that is correct.
At least `licensed status` doesn't return any errors now.

Have a good New Year!

Peter

**Comment by joshmgross** [comment]
Thanks @PeterNitscheMI!

>I have updated the license cache using the licensed cache command of licensed version 2.12.2.
A lot of licenses have been removed and I'm not sure if that is correct.
At least licensed status doesn't return any errors now.

Might be a version difference with `licensed` 🤔. CI is passing, so it's good for now. I'll update licenses separately from this PR.

**Review by joshmgross — APPROVED** [review]

**Pull request merged**
