### PR TITLE
Update Oktokit dependencies.

### LINKED ISSUE #133: TypeError: github.repos.createOrUpdateEnvironment is not a function - Octokit.js Support up-to-date?
**Is your feature request related to a problem? Please describe.**
Trying to use github-script for environments but getting this error message:
`TypeError: github.repos.createOrUpdateEnvironment is not a function`

**Describe the solution you'd like**
Would you all be able to update the version of Octokit.js that supports [Repo Environments](https://octokit.github.io/rest.js/v18#repos-create-or-update-environment)

**Describe alternatives you've considered**
Using actions to post the HTTP response for environment creation

**Additional context**
image

### PR DESCRIPTION
**Pull request by IronSean**
A number of oktokit api methods were unavailable in the current version of this action, I bumped them to their highest available non-breaking versions. There's a version 5.*.* of @octokit/plugin-rest-endpoint-methods but it moves all of the API endpoints from `oktokit.*` to `oktokit.rest.*` which would be a breaking change for users of the github-script action, so I leave that as a future exercise.

You can test my fork with `ironsean/github-script@v-test`.

Fixes #133

### CODE REVIEW

**Comment by kimmoahokas** [comment]
Could you update the `@actions` libraries as well? For example `@actions/core` 1.5.0 seems to bring quite a lot of new features.

**Comment by joshmgross** [comment]
👋  Hey @IronSean,

Thanks for this! It can be difficult to review package dependency updates in a safe manner due to the large number of changes. 

I've bumped all the minor versions in #192 

For fixing #133, we'll need to making some major version updates which will require a new major version of this action.

**Comment by IronSean** [comment]
@joshmgross I'm 10% disappointed I don't get to count as a contributor since you opened your own PR, but 90% happy that the fix is in and merged quickly 👍

**Comment by joshmgross** [comment]
Oops, sorry about that @IronSean.

I added you to https://github.com/actions/github-script/releases/tag/v5.0.0

**Pull request closed without merging**
