### PR TITLE
Make require relative to GitHub workspace

### PR DESCRIPTION
**Pull request by robyoung**
Change to the `GITHUB_WORKSPACE` directory before running the script so that callers do not have to explicitly use the `GITHUB_WORKSPACE` environment variable when requiring script files.

Workflow run steps are run within the GITHUB_WORKSPACE so this seems like the expected default.

### CODE REVIEW

**Comment by joshmgross** [comment]
@robyoung could this break existing uses of this action that assume the require *isn't* relative?

**Comment by robyoung** [comment]
Not that I can think of if they assume the require isn't relative. If an absolute path is provided it still works as expected because in those cases the current working directory is irrelevant.

Uses that depend on whatever the current working directory is now would break (assuming that is different to `GITHUB_WORKSPACE`) but I think that's ok as it's explicitly unsupported in the README.

**Comment by robyoung** [comment]
@joshmgross is there anything else you need before this can be merged?

**Comment by joshmgross** [comment]
👋  Hey @robyoung, sorry for the delay. I'll try to test this out next week and get it merged.

**Comment by robyoung** [comment]
Just rebased to resolve a conflict with the updated version. Any idea when this may get reviewed @joshmgross

**Comment by joshmgross** [comment]
👋  Hey @robyoung, apologies again for the delay. The changes look good to me but I need to run through a few test scenarios to make sure we're not breaking any existing uses.

**Comment by jclem** [comment]
Unfortunately, relative requires not working isn't because of the working directory (actions run by default in the `GITHUB_WORKSPACE`, as it is). Instead, it's because `require` resolves paths relative to the module—in this case, the module location is where the `actions/github-script` action was downloaded to on the runner.

This is why although tests pass in this fork, calls to `require` relative to the workspace still will not function. I'm still searching for a way to resolve this.

**Comment by joshmgross** [comment]
#135 should fix this

**Pull request closed without merging**
