### PR TITLE
Adding @actions/exec to github-script

### PR DESCRIPTION
**Pull request by bhavanakonchada**
The `@actions/exec` package is useful to execute tools in a cross platform way. This package is now available to the script using the `exec` variable.

### CODE REVIEW

**Review by joshmgross — COMMENTED** [review]
👋  Hey, thanks for this contribution. It looks like a large change was made to `package-lock.json` switching from `lockfileVersion` `2` to `1` - https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

Since we're already on a newer version, I'd prefer not go back to version 1. Could you update your version of `npm` and re-run `npm install`?

I'd be happy to help with that change if you'd like.

**Comment by bhavanakonchada** [comment]
> 👋 Hey, thanks for this contribution. It looks like a large change was made to `package-lock.json` switching from `lockfileVersion` `2` to `1` - https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion
> 
> Since we're already on a newer version, I'd prefer not go back to version 1. Could you update your version of `npm` and re-run `npm install`?
> 
> I'd be happy to help with that change if you'd like.

@joshmgross thanks so much for taking a keen look at the PR, updated npm as you suggested to ensure `package-lock.json` is now at version 2.

**Comment by bhavanakonchada** [comment]
Hi @joshmgross , do you believe this PR can be merged, after the checks passing and incorporating feedback ?

**Review by joshmgross — APPROVED** [review]

**Comment by joshmgross** [comment]
👋  Hey @bhavanakonchada, thanks for your contribution!

This is now available in https://github.com/actions/github-script/releases/tag/v4.1.0, which can be accessed with the following refs in your workflow:
- `main`
- `v4.1.0`
- `v4.1`
- `v4`

**Pull request merged**
