### PR TITLE
Upgraded npm packages to latest and cached licenses

### PR DESCRIPTION
**Pull request by guyarb**

### CODE REVIEW

**Comment by guyarb** [comment]
@jclem

**Comment by JJ** [comment]
Well, leaving it within v3 would help to not break existing builds... At the end of the day, there's nothing changing in the API. But I guess that's what you mean after all.

**Comment by guyarb** [comment]
> Well, leaving it within v3 would help to not break existing builds... At the end of the day, there's nothing changing in the API. But I guess that's what you mean after all.

Of course, I meant to keep V3 pointed to the new master.
Thanks for the clarification

**Comment by JJ** [comment]
I wonder if it wouldn't make more sense to just fork this and start using forked versions?

**Comment by guyarb** [comment]
> I wonder if it wouldn't make more sense to just fork this and start using forked versions?

I think not
It will be only a temporary workaround. The correct way is to wait (or ping @jclem somehow) for the fix to be in the master.

**Comment by jclem** [comment]
@guyarb Can you provide a bit more context on what's being updated in your PR description? The latest release `v3.0.1` has the required actions-core update, which should fix failing workflows.

**Comment by jclem** [comment]
My bad, meant to hit "Comment" and hit "Close with comment" on accident.

**Pull request closed without merging**
