### PR TITLE
Add @actions/cache to dependencies

### PR DESCRIPTION
**Pull request by mmkal**
I have a use case where I'd like to use the github-script action and save/restore caches through the `@actions/cache` API. I had a look at the code and it looks like it's possible to just mimic what's being done with `@actions/io` and `@actions/glob` - so thought I'd just create a PR rather than raise an issue.

The tests passed so please let me know if there's anything else I should do here!

### CODE REVIEW

**Comment by joshmgross** [comment]
👋 Hey @mmkal, could you describe your use case a bit more?

If you're creating a workflow that relies on `@actions/cache`, you might be better off writing your own action rather than using `github-script`.

**Comment by JamesMGreene** [comment]
@mmkal If you have a JavaScript-centric project, you could also just add it as a dependency in your own `package.json` (or just do a one-off `npm install @actions/cache` in your Actions workflow steps) and then `require` it within the `@actions/github-script` step's `script` body.

**Comment by mmkal** [comment]
@joshmgross the use case is just some conditional logic for cache restoring that was getting very difficult to encode in yaml. I don't know if an action would make sense though because the logic is very specific to the monorepo that this was needed for.

@JamesMGreene yes right now I am doing a one-off install of the `@actions/cache` tool, but this won't be detected by Renovate, or other tools which read package.json files and workflow .yml files for actions/packages with CVEs. To avoid that problem, I'd need to do a full repo install of thousands of packages just for the sake of this one.

Having said all that, I ended up using a different tool which manages caches outside of GitHub, so I don't have a desperate need for this right now. I still think it fits fine in here, but feel free to close if you're unconvinced.

**Comment by joshmgross** [comment]
>I don't know if an action would make sense though because the logic is very specific to the monorepo that this was needed for.

You can create and define an action local to your repository - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow

Going to close this out, I don't think the extra dependency is worth adding to this action without a strong use case.

**Pull request closed without merging**
