### PR TITLE
Readme: fix env variable usage

### PR DESCRIPTION
**Pull request by mabar**

### CODE REVIEW

**Comment by jclem** [comment]
Hey @mabar can you provide some context on this? The correct way of reading an environment variable in Node.js is from the `process.env` object. I don't believe any `env` object is in scope here.

**Comment by mabar** [comment]
Hi @jclem 

This is a perfectly working action which works with `${{ env.php-extensions }}`
https://github.com/orisai/localization/actions/runs/341294087/workflow#L35-L40

example

If I change it accordingly to docs, it's just a plain string.
https://github.com/orisai/localization/actions/runs/342176353/workflow#L36-L41

example-2

I am sorry if I missed something but from my point of view works the same `${{ <env.variable> }}` syntax which works across all github actions and `${process.env.variable}` is not working

**Comment by jclem** [comment]
Ah, the difference is that this is using JavaScript template strings, which is evaluated by Node.js at runtime:

```javascript
script: return `${process.env.FOO}`
```

And this is using Actions' own interpolation syntax, which interpolates raw values into your workflow when the action it self is built before it runs:

```javascript
script: return "${{ env.some-key }}"
```

There's an unfortunately similarity between JavaScript template string syntax and this Actions interpolation syntax, but there are few syntax options for interpolation that wouldn't have similarity or outright conflict somewhere.

**Comment by mabar** [comment]
Would be nice to add this clarification into docs then. As I never used Node.js I don't know this syntax so the only one example on usage of env variables in script was kinda misleading for me.

**Comment by jclem** [comment]
That's a good point @mabar. I hadn't considered that some users would be familiar with JavaScript, but less so with Node.js Thank you! I will improve the readme to address this.

**Pull request closed without merging**
