### PR TITLE
feat(build): use husky for pre-commit

### PR DESCRIPTION
**Pull request by francisfuzz**
This PR updates `package.json` to include [`husky`](https://github.com/typicode/husky) as a `devDependency`, moving the precommit step from `scripts` to `husky` as suggested [by their documentation](https://github.com/typicode/husky#install).

cc: @jclem for review

### CODE REVIEW

**Comment by jclem** [comment]
@francisfuzz Can you remove the change to `dist/index.js` in this? Then should be good to go.

**Comment by francisfuzz** [comment]
> Can you remove the change to dist/index.js in this? Then should be good to go.

I'll do that, will follow up here when it's finished 👌

**Comment by francisfuzz** [comment]
@jclem - While I'm totally up to make that change, I'm wondering why you don't want that newly updated `dist/index.js` file there? Is it because the changes in scope are only related to husky rather than source file itself?

As an aside -- I'd like to figure out what's happening on my local machine that's actually hardcoding values of my local copy into the `dist/index.js` upon compilation of the Typescript source file. Not sure what's happening there.

**Comment by jclem** [comment]
@francisfuzz Are the dist/index.js changes related to the PR? It seems to be adding things like your computer home directory path.

**Comment by jclem** [comment]
Ugh, I tried fixing it but can't get rid of the newline.

**Pull request merged**
